apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: example-namespace

# transformers:
# - krm-func.yaml

functions:
- type: transformer
  spec:
    container:
      image: myimage:latest #ghcr.io/workday/cuestomize:0.3.0
      network: true
  path: krm-func.yaml

# functions:
# - type: transformer
#   spec:
#     image: ghcr.io/workday/cuestomize:latest
#     network: true
#   path: krm-func.yaml
